name: cs7643-a3
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - pyyaml=5.4.1
  - matplotlib
  - scipy
  - future
  - pip
  - pytorch
  - torchvision
  - cpuonly  
  - captum


